version: "3.8"

networks:
  monitor:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /opt/container/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/container/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /opt/container/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitor
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - /opt/container/blackbox/config.yml:/etc/blackbox/config.yml
    ports:
      - "9115:9115"
    networks:
      - monitor
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /opt/container/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - monitor
    restart: unless-stopped

  traefik:
    image: traefik:v2.9
    container_name: traefik
    volumes:
      - /opt/container/traefik/acme.json:/acme.json
    ports:
      - "8050:8080"
    networks:
      - monitor
    restart: unless-stopped
