version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.40.2
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /opt/container/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/container/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - /opt/container/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=90d"
      - "--web.enable-lifecycle"
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: always
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - /opt/container/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitor

  grafana:
    image: grafana/grafana:9.2.5
    restart: always
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /opt/container/grafana/data:/var/lib/grafana
    networks:
      - monitor

  loki:
    image: grafana/loki:3.2.1
    restart: always
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "--config.file=/etc/loki/loki-config.yaml"
    volumes:
      - /opt/container/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - /opt/container/loki/data:/data/loki
    networks:
      - monitor

  promtail:
    image: grafana/promtail:3.2.1
    restart: always
    container_name: promtail
    volumes:
      - /opt/container/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
      - /opt/container/promtail/positions.yaml:/var/lib/promtail/positions.yaml
    command:
      - "--config.file=/etc/promtail/promtail-config.yaml"
    networks:
      - monitor

networks:
  monitor:
    external: true
